spring:
  data:
    rest:
      basePath: /api
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      url: jdbc:h2:file:~/project
      driverClassName: org.h2.Driver
      username: sa
      password: password
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework: ERROR
    com.gehc.edison.ai.project: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: dynamic-flow.log
